import type { Locator, Page } from '@playwright/test';

/**
 * Dashboard · Demo — `/dashboard`
 * Generated by Auto QA. Locators and their fingerprints: ../locators/dashboard.locators.json
 */
export class DashboardPage {
  static readonly path = '/dashboard';

  readonly dashboardHeading: Locator;
  readonly profileLink: Locator;

  constructor(private readonly page: Page) {
    this.dashboardHeading = page.getByRole('heading', { name: 'Dashboard', exact: true });
    this.profileLink = page.getByRole('link', { name: 'Profile', exact: true });
  }

  async goto(): Promise<void> {
    await this.page.goto(DashboardPage.path);
  }

  /**
   * S5 Click Profile
   */
  async openProfile(): Promise<void> {
    await this.profileLink.click();
  }
}
