import type { Locator, Page } from '@playwright/test';

/**
 * Login · Demo — `/`
 * Generated by Auto QA. Locators and their fingerprints: ../locators/login.locators.json
 */
export class LoginPage {
  static readonly path = '/';

  readonly username: Locator;
  readonly password: Locator;
  readonly loginButton: Locator;

  constructor(private readonly page: Page) {
    this.username = page.getByRole('textbox', { name: 'Username', exact: true });
    this.password = page.getByRole('textbox', { name: 'Password', exact: true });
    this.loginButton = page.getByTestId('login');
  }

  async goto(): Promise<void> {
    await this.page.goto(LoginPage.path);
  }

  /**
   * S2 Enter valid username
   * S3 Enter valid password
   * S4 Click the Login button
   */
  async login(username: string, password: string): Promise<void> {
    await this.username.fill(username);
    await this.password.fill(password);
    await this.loginButton.click();
  }
}
