import type { Locator, Page } from '@playwright/test';

/**
 * Profile · Demo — `/profile`
 * Generated by Auto QA. Locators and their fingerprints: ../locators/profile.locators.json
 */
export class ProfilePage {
  static readonly path = '/profile';

  readonly fullName: Locator;
  readonly countrySelect: Locator;
  readonly sendMeNewsCheckbox: Locator;
  readonly saveChangesButton: Locator;

  constructor(private readonly page: Page) {
    this.fullName = page.getByRole('textbox', { name: 'Full name', exact: true });
    this.countrySelect = page.getByRole('combobox', { name: 'Country', exact: true });
    this.sendMeNewsCheckbox = page.getByRole('checkbox', { name: 'Send me news', exact: true });
    this.saveChangesButton = page.getByRole('button', { name: 'Save changes', exact: true });
  }

  async goto(): Promise<void> {
    await this.page.goto(ProfilePage.path);
  }

  /**
   * S6 Enter Full name
   * S7 Select India from Country
   * S8 Check Send me news
   * S9 Click Save changes
   */
  async saveChanges(fullName: string, country: string): Promise<void> {
    await this.fullName.fill(fullName);
    await this.countrySelect.selectOption(country);
    await this.sendMeNewsCheckbox.check();
    await this.saveChangesButton.click();
  }
}
