import { type Page, test as base } from '@playwright/test';
import { markStep, startLog } from '../utils/matchers';

/**
 * Shared test setup, generated by Auto QA.
 *
 * - Health check (FR-VAL-04): a test fails if the page threw an uncaught error, a request got a 5xx
 *   response, or an error page was shown. Switch it off for one test with the annotation
 *   `{ type: 'health', description: 'off' }`.
 * - Facts (FR-VAL-02): at the end of every test the page's URL, title, headings and visible messages
 *   are attached as `auto-qa-facts`, so a failure can say what actually happened.
 * - Pop-ups: browser alerts and confirms are accepted and written down (as they were when the test was
 *   explored), so they never block the test and a check can say what they said.
 * - Evidence: `step()` takes a screenshot when each step ends, passed or failed.
 */
export const test = base.extend<{ autoQa: void }>({
  autoQa: [
    async ({ page }, use, testInfo) => {
      const problems: string[] = [];
      const log = startLog(page);
      const dialogs = log.dialogs;
      page.on('dialog', async (dialog) => {
        dialogs.push(`${dialog.type()} "${dialog.message()}"`);
        await dialog.accept().catch(() => undefined);
      });
      page.on('pageerror', (error) => problems.push(`uncaught error: ${error.message}`));
      page.on('response', (response) => {
        if (response.status() >= 500)
          problems.push(`${response.status()} from ${response.request().method()} ${new URL(response.url()).pathname}`);
      });

      await use();

      const facts = await readFacts(page).catch(() => undefined);
      if (
        facts &&
        /internal server error|bad gateway|service unavailable|^50[0-4]\b/i.test(
          `${facts.title}\n${facts.headings.join('\n')}`,
        )
      ) {
        problems.push(`error page shown: "${facts.headings[0] ?? facts.title}"`);
      }
      await testInfo.attach('auto-qa-facts', {
        body: JSON.stringify({ ...facts, problems, dialogs }),
        contentType: 'application/json',
      });

      const off = testInfo.annotations.some((a) => a.type === 'health' && a.description === 'off');
      if (!off && problems.length && testInfo.status === testInfo.expectedStatus) {
        throw new Error(`Health check failed: ${problems.join('; ')}`);
      }
    },
    { auto: true },
  ],
});
// The checks beyond Playwright's own: `expect(...).toBeCentered()`, `expectRequest(page, …)` and the rest.
export * from '../utils/matchers';

/** A test step that keeps a screenshot of the page when it ends, passed or failed (FR-EV-01). */
export async function step(title: string, page: Page, body: () => Promise<void>): Promise<void> {
  markStep(page);
  await test.step(title, async () => {
    try {
      await body();
    } finally {
      if (!page.isClosed()) {
        // A file, not in-memory data, so the reporter can find it and the platform can keep it.
        const info = test.info();
        const file = info.outputPath(`step-${info.attachments.length + 1}.png`);
        const saved = await page.screenshot({ path: file, animations: 'disabled' }).then(
          () => true,
          () => false,
        );
        if (saved) await info.attach(`step: ${title}`, { path: file, contentType: 'image/png' });
      }
    }
  });
}

/** What the page shows now: the facts an "actual result" is built from. */
async function readFacts(page: Page) {
  if (page.isClosed()) return undefined;
  const shown = await page.evaluate(() => {
    const visible = (el: Element) => {
      const r = (el as HTMLElement).getBoundingClientRect();
      const s = getComputedStyle(el);
      return r.width > 0 && r.height > 0 && s.visibility !== 'hidden' && s.display !== 'none';
    };
    const text = (el: Element) => (el.textContent ?? '').replace(/\s+/g, ' ').trim().slice(0, 160);
    const unique = (list: string[]) => [...new Set(list.filter(Boolean))].slice(0, 5);
    const headings = unique([...document.querySelectorAll('h1, h2, [role=heading]')].filter(visible).map(text));
    const messages = unique(
      [
        ...document.querySelectorAll(
          '[role=alert], [role=status], [aria-live], [class*="error" i], [class*="alert" i], [data-test*="error" i]',
        ),
      ]
        .filter(visible)
        .map(text),
    );
    const invalid = unique(
      [...document.querySelectorAll('input, select, textarea')]
        .filter((el) => !(el as HTMLInputElement).validity.valid)
        .map((el) => (el as HTMLInputElement).validationMessage),
    );
    return { headings, messages, invalid };
  });
  return { url: page.url(), path: new URL(page.url()).pathname, title: await page.title(), ...shown };
}

/** Values for `{{unique.email}}` and friends (FR-TD-04): new on every run. */
export function generate(name: string): string {
  const stamp = Date.now().toString(36);
  switch (name) {
    case 'unique.email':
      return `auto-qa.${stamp}@example.com`;
    case 'unique.number':
      return String(Date.now() % 1_000_000_000);
    case 'unique.text':
      return `auto-qa-${stamp}`;
    case 'today':
      return new Date().toISOString().slice(0, 10);
    default:
      throw new Error(`Unknown generator ${name}`);
  }
}
